### ISSUE TITLE
Incorrect dependency for Kotlin library

### ISSUE THREAD

**Issue by cypherdare** [CypherCove/gdx-tween#1]
@czyzby, I was wondering if you could look at this. This project has two library artifacts, `gdxtween`, and `gdxtween-kt`. The Kotlin one depends on the core library using `api project(":gdxtween")`, but the POM dependency comes out as 
```xml
      <groupId>gdx-tween</groupId>
      <artifactId>gdxtween</artifactId>
      <version>unspecified</version>
``` 
when I publish the library.

Looking at https://github.com/libktx/ktx, I see that `assets-async` similarly depends on `async` using  `compile project(':async')`. My understanding is that `api` is the same as `compile` from older Gradle versions.

**Comment by czyzby** [comment]
I believe you're correct, `api` supposedly works like `compile` (which seems to be deprecated). You can also try using `implementation`, although I'm not sure if this is the correct approach in this case. My current approach to Gradle configuration files is "don't touch if not broken", so we're still using `compile` in KTX - it seems to produce correct artifacts for now.

Are you sure you are correctly defining a `version` for each of your libraries? Not sure if this is the cause of the issue, but [KTX is using this](https://github.com/libktx/ktx/blob/master/build.gradle#L57) to set the version of the Gradle project.

**Comment by cypherdare** [comment]
That was the issue. It must be pulling the version from the project version when it translates the gradle module dependency into a POM dependency. It fixed it for my local Maven. But I did something else that messed up the Bintray artifacts...

Thanks for taking a look!
